Fixing Chef::Exceptions::EnclosingDirectoryDoesNotExist in Sublime Text 2 recipe
Fixes case where "#{node['sprout']['home']}/Library/Application Support" does not exist

Error: https://gist.github.com/6282553